apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/intive-RedHat-Devex-demo/demo-micro-service.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-microservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
