apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubernetes-actions
spec:
  params:
    - name: script
      description: The script to run
      type: string
  steps:
    - name: run-script
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e
        $(params.script)
