apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: demo-microservice-triggertemplate
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: demo-microservice-pipeline-run-
    spec:
      pipelineRef:
        name: demo-microservice-pipeline
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      params:
      - name: git-revision
        value: $(tt.params.git-revision)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: demo-microservice-triggerbinding
spec:
  params:
  - name: git-revision
    value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: demo-microservice-eventlistener
spec:
  triggers:
  - bindings:
    - ref: demo-microservice-triggerbinding
    template:
      ref: demo-microservice-triggertemplate
